# Generated by Django 5.0.2 on 2024-02-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image_1',
            field=models.ImageField(upload_to='sttic/project_images/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image_2',
            field=models.ImageField(upload_to='staic/project_images/'),
        ),
    ]
